"""Add post_type, media_files, story_elements to Post model and create new tables

Revision ID: 695cef866b9b
Revises: 
Create Date: 2025-07-15 21:15:23.868416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695cef866b9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_metrics', schema=None) as batch_op:
        batch_op.alter_column('metric_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('metric_value',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('story_elements')
        batch_op.drop_column('media_files')
        batch_op.drop_column('post_type')

    with op.batch_alter_table('story_templates', schema=None) as batch_op:
        batch_op.alter_column('template_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_templates', schema=None) as batch_op:
        batch_op.alter_column('template_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('media_files', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('story_elements', sa.TEXT(), nullable=True))

    with op.batch_alter_table('post_metrics', schema=None) as batch_op:
        batch_op.alter_column('metric_value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metric_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
