"""Add post_type, media_files, story_elements to Post model

Revision ID: 8a0bd78fd291
Revises: 695cef866b9b
Create Date: 2025-07-15 21:25:39.563150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0bd78fd291'
down_revision = '695cef866b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('media_files', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('story_elements', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('story_elements')
        batch_op.drop_column('media_files')
        batch_op.drop_column('post_type')

    # ### end Alembic commands ###
